### ISSUE TITLE
Error when editing .vue file in VS 2015

### ISSUE THREAD

**Issue by cybertino** [madskristensen/VuePack#1]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.0.10
### Description

Error occurred while modifying **script** section of .**vue** file.
### Steps to recreate
1. Create new .vue file
2. Create **script** block
3. Type `module.exports = {` and hit Enter.
### Current behavior

Object reference is not set to an instance of object.
### Screenshot

![screenshot_1](https://cloud.githubusercontent.com/assets/12428252/15378354/d3387a54-1db6-11e6-9ce2-ffb7f599171d.png)

**Comment by madskristensen** [comment]
Thanks for the bug report. I cannot reproduce the issue. Do you have any extensions installed that might interfere with HTML/JavaScript editing?

**Comment by cybertino** [comment]
I have Web Essentials and Web Compiler (that's what I manually installed). Do you need a full list?

**Comment by madskristensen** [comment]
Can you try to disable the extensions one by one to see which one is the problem?

**Comment by softomatix** [comment]
Ok. Will do it one

**Comment by cybertino** [comment]
Tried to disable manually installed extensions but still have the same problem. Also the syntax is not highlighting for the **script** section.

![screenshot_1](https://cloud.githubusercontent.com/assets/12428252/15492009/a8e353ba-21ca-11e6-92c8-648335d178d5.png)

**Comment by cybertino** [comment]
The issue still persists to me but it seems like my local problem. Is VS2015 Update 3 supported?
